### PR TITLE
All Simplification and Errors

### PR DESCRIPTION
**Pull request by HalflingHelper**
## Changes
- Commas in `all`, `arbitrary`, and theorem instantiation are now syntactic sugar
  - Removed lists from AST nodes, and added position property to allow for pretty printing.
- Error message suggesting a type argument when someone forgets it (https://github.com/jsiek/deduce/issues/27)

## Possible Enhancements
- [] Factor out repeated code for wrapping and desugaring
  - I want to make sure that it's still clear what the code is doing
  - I didn't see anywhere obvious to add utility functions

### CODE REVIEW

**Comment by jsiek** [comment]
Calvin, this is great!
Have you run `test-deduce.py` to check that all the tests still pass?
Did you add any new tests or change the errors that arise from old tests?

**Comment by HalflingHelper** [comment]
Oh I just pulled in that addition from Shulin, looks like I have one or two small things to fix.

**Comment by HalflingHelper** [comment]
Some of these should error also seem to have sub-optimal error messages caused by private imports thing, so I'm changing these to import Nat.

i.e.
```
./test/should-error/inst-type-square-bracket.pf:4.17-4.18: undefined variable `suc`	(uniquify)
```

**Comment by jsiek** [comment]
ok, I'll wait for you to commit those further changes before I merge this PR

**Pull request merged**
