### PR TITLE
Suffices terminst advice

### PR DESCRIPTION
**Pull request by HalflingHelper**
#42

### CODE REVIEW

**Comment by HalflingHelper** [comment]
Passing all tests, and I added two more where advice should / shouldn't be given. It might be worth taking some time to brainstorm more situations when this could arise, though as arguments of calls is certainly the most common.

**Comment by HalflingHelper** [comment]
Wait to merge this, there might be a problem with the operator fix : 
```
suffices to prove:
        a + sum(d) = + a
```

**Comment by HalflingHelper** [comment]
Also the lalr parser doesn't like this :)
theorem foldr_eq_sum : all ls : List<Nat>. sum(ls) = foldr(ls, 0, operator +)

**Comment by HalflingHelper** [comment]
It's the paren after operator+

**Comment by HalflingHelper** [comment]
Closing since https://github.com/jsiek/deduce/commit/0e88ca917e471eadf085805b71f9de83a0d760d7 appears to fix

**Comment by jsiek** [comment]
Interesting. You're solution is a more specific that what I just pushed, which could make it less verbose, which is good, but the question is whether `Call` is the only problematic context...

**Comment by jsiek** [comment]
I suspect that there are more contexts that could be problematic... any place in synthesis mode.

**Comment by jsiek** [comment]
So the really good solution would be to augment the `substitute` method to know about check/synthesis and only set `inferred = False` when substituting in a synthesis context. But that's a bunch more work. I'll make an issue for that.

**Comment by jsiek** [comment]
Hmm, actually, it's not as simple as recognizing synthesis mode because of generic functions.

**Comment by jsiek** [comment]
I think perhaps the fix I just pushed is good because it is conservative and not that complicated. To do better seems to require a **much** more complex solution.

**Pull request closed without merging**
